### ISSUE TITLE
Providing GPR shadow sets

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-fast-interrupt#139]
raised by AIA group as potentially useful for fast interrupt group in email.

- Providing GPR Shadow Sets.
The EIC has the ability to specify a GPR Shadow Set that the interrupt handler can use, w/o executing a GPR save/restore sequence in the handler. The EIC specifies the Shadow Set to be used by the hart. The tradeoff is eliminating the save/restore sequence against adding area/power for the shadow GPR sets, which is significant. Given the cost, the likelihood of this being a valuable architectural feature is low.

**Comment by kasanovic** [comment]
Seems to be a general trend away from this due to cost/power, especially for multiple preemption levels.  Software can save/restore only those registers needed. Handlers would be software-incompatible ( but difference could be constrained to trampoline code in software-vectored scheme if common ABI used for handlers).   For the class of cores using CLIC, probably explicit push/pop instructions are more useful than interrupt register banks.
