### ISSUE TITLE
Change thresholding CSRs to not have packed version

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-fast-interrupt#38]
Not clear we need packed CSR for thresholds at different privilege.

**Comment by dansmathers** [comment]
draft 20200423 has xintthresh instead of only having mintthresh.

 (NEW) 0xm??   xintthresh   Interrupt-level threshold

New Interrupt-Level Threshold (xintthresh) CSRs
The interrupt-level threshold (xintthresh) is a new read-write CSR, which holds an 8-bit field (th) for the threshold level of the associated privilege mode.

**Comment by Kevin-Andes** [comment]
This was fixed in 20191120 and no longer have thresholds of multiple privilege modes packed in a single CSR.
